# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprofile',
            name='character',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cgame', to='games.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='userprofile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cprofile', to='accounts.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='youtubelink',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
