# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180405_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_online',
            field=models.DateField(auto_now_add=True),
        ),
    ]
