# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180405_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterprofile',
            name='fun',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='characterprofile',
            name='serious',
            field=models.BooleanField(default=True),
        ),
    ]
