# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_playing_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='main_character',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maincharacter', to='accounts.CharacterProfile'),
        ),
    ]
