# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_main_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
