# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20180410_1312'),
        ('accounts', '0007_userprofile_img_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='games.Game')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='accounts.Attributes')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characterattributes', to='accounts.CharacterProfile')),
            ],
        ),
    ]
