# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_attributes_attributevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to='accounts.CharacterProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='character',
        ),
        migrations.AddField(
            model_name='attributechoices',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributechoice', to='accounts.AttributeValue'),
        ),
    ]
