# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-20 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180411_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img_profile',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
