# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_online',
            field=models.DateField(auto_now=True),
        ),
    ]
