# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_img_tall'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='img_logo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
