# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0004_remove_order_expiredate'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='express',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
