# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_privatechat_privatemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='chatroom.PrivateChat'),
        ),
    ]
